_target_: dataset.tartandrive.TartanDriveSequence
name: "TartanDrive2"

root: data/TartanDrive2
geo_tiff_path: ${.root}/gascola_EPSG32617_scale03_082725.tiff

ground_image_resize: [518, 518]
aerial_image_resize: [768, 768]

scenes:
  # # Seen routes
  # - 2023-11-14-14-52-22_gupta
  # - figure_8_2023-09-14-12-48-02
  # - figure_8_morning_slow_2023-09-12-11-06-32
  # - gupta_2023-09-14-11-12-19
  # - warehouse_gupta_skydio_2023-09-13-16-45-20
  # - warehouse_to_fence_2023-09-12-10-19-17
  # # Unseen routes
  # - 2023-11-02-16-00-43_down_meadows
  # - figure_8_to_turnpike_pt2_2023-09-12-12-28-48
  # - meadow_turnpike_2023-09-14-13-35-35
  # - rough_rider_2023-09-14-12-57-00
  # - sam_loop_2023-09-27-13-04-54
  # - turnpike_2023-09-12-12-39-19
  # - turnpike_2023-09-12-12-53-32
  # - turnpike_2023-09-13-18-09-45
  # - turnpike_2023-09-13-18-37-40
  # - turnpike_2023-09-14-13-20-40
  # - turnpike_skydio_2023-09-13-18-00-11
  # - turnpike_flat_2023-09-12-13-11-44
  # - turnpike_2023-09-13-18-42-57
  - turnpike_flat_2023-09-12-13-42-26
  # - turnpike_2023-09-13-18-15-03
  # - 2023-10-26-14-42-35_turnpike_afternoon_fall
