_target_: dataset.arl_jackal.ARLJackalDataset
name: "ARL_Jackal_ahg"

root: data/ARL_Jackal
geo_tiff_path: ${.root}/ut_ahg_EPSG32614_scale01_080425.tiff

ground_image_resize: [518, 518]
aerial_image_resize: [768, 768]

# --- sampling parameters ---
n_poses: 128
dist_bounds: [2.0, 100.0] # (m)
r_bounds: [-60.0, 60.0] # (deg)
radial_power: 1.0

# --- data augmentation ---
center_jitter: 10.0
scale_bounds: [0.7, 1.5]
rotate_augment: True
color_augment: 1.0
depth_dropout: 0.2

train_scenes:
  - ahg_courtyard_2025_07_03-18_17_34

val_scenes:
  - ahg_courtyard_2025_07_03-18_09_49
